name = "fbcoord"
main = "src/worker.ts"
compatibility_date = "2026-04-04"

[[durable_objects.bindings]]
name = "FBCOORD_POOL"
class_name = "PoolDurableObject"

[[durable_objects.bindings]]
name = "FBCOORD_REGISTRY"
class_name = "RegistryDurableObject"

[[durable_objects.bindings]]
name = "FBCOORD_TOKEN_STORE"
class_name = "TokenDurableObject"

[assets]
directory = "./ui/dist"
binding = "ASSETS"

[[migrations]]
tag = "v1"
new_classes = ["PoolDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["RegistryDurableObject", "TokenDurableObject"]
