name = "fbcoord"
main = "src/worker.ts"
compatibility_date = "2026-04-04"

[[durable_objects.bindings]]
name = "FBCOORD_POOL"
class_name = "PoolDurableObject"

[[durable_objects.bindings]]
name = "FBCOORD_REGISTRY"
class_name = "RegistryDurableObject"

[[durable_objects.bindings]]
name = "FBCOORD_TOKEN_STORE"
class_name = "TokenDurableObject"

[[durable_objects.bindings]]
name = "FBCOORD_AUTH_GUARD"
class_name = "AuthGuardDurableObject"

[[kv_namespaces]]
binding = "FBCOORD_AUTH_KV"
id = "18c8b11112c14f938c5d79d023e04c9e"
preview_id = ""

[assets]
directory = "./ui/dist"
binding = "ASSETS"

[vars]
FBCOORD_ABORTED_NOTIFY_DELAY_MS = "30000"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PoolDurableObject"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RegistryDurableObject", "TokenDurableObject"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["AuthGuardDurableObject"]
